---
- name: DEPLOY AS3 DEC (title)
  hosts: localhost
  connection: local
  gather_facts: no



  vars:


  vars_files:
    - ./cred/big_cred.yaml



  tasks:
  - name: AS3 Create VIP
    uri:
      url: https://35.176.82.189/mgmt/shared/appsvcs/declare
      user: "{{ bigip_user }}"
      password: "{{ bigip_pass }}"
      method: POST
      body: "{{ lookup('file','as3.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: False
...

